<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>false</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>IIoT.Edge.UI.Shared.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\fonts\iconfont.ttf" />
    <None Remove="Assets\images\icon.ico" />
    <None Remove="Assets\images\login1.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IIoT.Edge.SharedKernel\IIoT.Edge.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\fonts\iconfont.ttf" />
    <AvaloniaResource Include="Assets\images\icon.ico" />
    <AvaloniaResource Include="Assets\images\login1.png" />
  </ItemGroup>

</Project>
