using IIoT.Edge.UI.Avalonia.Localization;

namespace IIoT.Edge.Presentation.Navigation.Avalonia.Localization;

public sealed class NavigationAvaloniaZhCnResources : IAvaloniaResourceContributor
{
    public string CultureName => "zh-CN";

    public IReadOnlyDictionary<string, string> GetResources()
        => new Dictionary<string, string>
        {
            ["Navigation_Menu_Data"] = "生产数据",
            ["Navigation_Menu_Capacity"] = "产能",
            ["Navigation_Menu_HardwareConfig"] = "硬件配置",
            ["Navigation_Menu_Monitor"] = "监控",
            ["Navigation_Menu_Io"] = "IO 交互",
            ["Navigation_Menu_Recipe"] = "产品配方",
            ["Navigation_Menu_ParamConfig"] = "参数配置",
            ["Navigation_Menu_PlcTaskBinding"] = "PLC 任务",
            ["Navigation_Menu_CoreDiagnostics"] = "系统诊断",
            ["Navigation_Title_IoInteract"] = "IO 交互",
            ["Navigation_Title_HardwareConfig"] = "硬件配置",
            ["Navigation_Title_ProductRecipe"] = "产品配方",
            ["Navigation_Title_ParamConfig"] = "参数配置",
            ["Navigation_Title_IoInteractionGroup"] = "交互点位",

            ["Navigation_Tab_NetworkDevice"] = "网络设备",
            ["Navigation_Tab_SerialDevice"] = "串口设备",
            ["Navigation_Tab_IoMapping"] = "IO 映射",
            ["Navigation_Tab_MesParams"] = "MES 参数",
            ["Navigation_Tab_CloudParams"] = "云端参数",
            ["Navigation_Tab_PluginBusinessParams"] = "插件业务参数",

            ["Navigation_Button_Query"] = "查询",
            ["Navigation_Button_Export"] = "导出",
            ["Navigation_Button_Save"] = "保存",
            ["Navigation_Button_SyncCloud"] = "同步云端",
            ["Navigation_Button_SwitchSource"] = "切换来源",
            ["Navigation_Button_Add"] = "新增",
            ["Navigation_Button_Delete"] = "删除",
            ["Navigation_Button_Cancel"] = "取消",
            ["Navigation_Button_Confirm"] = "确认",
            ["Navigation_Button_Write"] = "写入",
            ["Navigation_Button_AddInteraction"] = "新增交互点",
            ["Navigation_Button_AddDataPoint"] = "新增数据点",

            ["Navigation_Column_Time"] = "时间",
            ["Navigation_Column_BatchNo"] = "批次",
            ["Navigation_Column_Total"] = "总数",
            ["Navigation_Column_Ok"] = "良品",
            ["Navigation_Column_Ng"] = "不良",
            ["Navigation_Column_Yield"] = "良率",
            ["Navigation_Column_DeviceName"] = "设备",
            ["Navigation_Column_DeviceType"] = "类型",
            ["Navigation_Column_DeviceModel"] = "型号",
            ["Navigation_Column_ModuleId"] = "模块",
            ["Navigation_Column_IpAddress"] = "IP 地址",
            ["Navigation_Column_Port1"] = "端口 1",
            ["Navigation_Column_Port2"] = "端口 2",
            ["Navigation_Column_Command1"] = "命令 1",
            ["Navigation_Column_Command2"] = "命令 2",
            ["Navigation_Column_TimeoutMs"] = "超时(ms)",
            ["Navigation_Column_Enable"] = "启用",
            ["Navigation_Column_Remark"] = "备注",
            ["Navigation_Column_PortName"] = "端口",
            ["Navigation_Column_BaudRate"] = "波特率",
            ["Navigation_Column_DataBits"] = "数据位",
            ["Navigation_Column_StopBits"] = "停止位",
            ["Navigation_Column_Parity"] = "校验",
            ["Navigation_Column_PlcAddress"] = "PLC 地址",
            ["Navigation_Column_Count"] = "数量",
            ["Navigation_Column_BusinessGroup"] = "业务组",
            ["Navigation_Column_SignalName"] = "信号名称",
            ["Navigation_Column_DataType"] = "数据类型",
            ["Navigation_Column_Direction"] = "方向",
            ["Navigation_Column_Editable"] = "可编辑",
            ["Navigation_Column_Status"] = "状态",
            ["Navigation_Column_Message"] = "信息",
            ["Navigation_Column_TaskKey"] = "任务 Key",
            ["Navigation_Column_Signal"] = "信号",
            ["Navigation_Column_Binding"] = "绑定",
            ["Navigation_Column_Address"] = "地址",
            ["Navigation_Column_CurrentValue"] = "当前值",
            ["Navigation_Column_InteractionItem"] = "交互项",
            ["Navigation_Column_PlcSignal"] = "PLC 信号",
            ["Navigation_Column_PlcValue"] = "PLC 值",
            ["Navigation_Column_CurrentReply"] = "当前应答",
            ["Navigation_Column_ReplyValue"] = "应答值",
            ["Navigation_Column_WriteValue"] = "写入值",
            ["Navigation_Column_Action"] = "操作",
            ["Navigation_Column_Index"] = "序号",
            ["Navigation_Column_MatrixValues"] = "矩阵值",
            ["Navigation_Column_ParamName"] = "参数名称",
            ["Navigation_Column_ParamValue"] = "参数值",
            ["Navigation_Column_ParamType"] = "参数类型",
            ["Navigation_Column_DefaultValue"] = "默认值",
            ["Navigation_Column_LowerLimit"] = "下限",
            ["Navigation_Column_UpperLimit"] = "上限",
            ["Navigation_Column_Unit"] = "单位",

            ["Navigation_Dialog_Title_Pending"] = "待确认",
            ["Navigation_Dialog_Message_Pending"] = "请确认本次操作。",
            ["Navigation_Dialog_AddIoPoint"] = "新增 IO 点位",
            ["Navigation_Dialog_AddInteraction"] = "将为当前网络设备新增一个交互点位。",
            ["Navigation_Dialog_AddDataPoint"] = "将为当前网络设备新增一个数据点位。",
            ["Navigation_Dialog_Title_SaveHardwareConfig"] = "保存硬件配置",
            ["Navigation_Dialog_Message_SaveHardwareConfigReadonly"] = "当前为 Avalonia 迁移验证，不写入真实硬件配置。",
            ["Navigation_Status_ReadOnlyValidation"] = "只读验证模式",
            ["Navigation_Status_AddInteractionPending"] = "新增交互点位待确认",
            ["Navigation_Status_AddDataPointPending"] = "新增数据点位待确认",
            ["Navigation_Status_SavePending"] = "保存确认待执行",

            ["Navigation_Io_ManualRead"] = "手动读取",
            ["Navigation_Io_NoSignals"] = "当前设备没有可显示的 IO 点位。",
            ["Navigation_Io_DemoDeviceA"] = "PLC 交互站 A",
            ["Navigation_Io_DemoDeviceB"] = "PLC 数据站 B",
            ["Navigation_Io_SafeSkeletonMessage"] = "当前为 Avalonia I/O 骨架，手动读取和写入不会连接真实 PLC。",
            ["Navigation_Io_ManualReadPreviewUpdated"] = "已刷新页面预览值，未连接真实 PLC。",
            ["Navigation_Io_WriteRejected"] = "写入请求未被安全端口接受。",
            ["Navigation_Io_WritePreviewUpdated"] = "已更新写入预览值，未连接真实 PLC。",
            ["Navigation_Io_Direction_PlcToHost"] = "PLC 到上位机",
            ["Navigation_Io_Direction_HostToPlc"] = "上位机到 PLC",
            ["Navigation_Io_CollapseDetails"] = "收起明细",
            ["Navigation_Io_ViewDetails"] = "查看明细",
            ["Navigation_Io_NoContinuousValues"] = "暂无连续值",
            ["Navigation_Io_ArraySummaryFormat"] = "{0} 行 x {1} 项",
            ["Navigation_ListSeparator"] = "、",

            ["Navigation_Label_Version"] = "版本",
            ["Navigation_Label_Process"] = "工序",
            ["Navigation_Label_Update"] = "更新时间",
            ["Navigation_Label_Source"] = "来源",
            ["Navigation_Label_EmergencyEdit"] = "本地应急编辑",
            ["Navigation_Hint_ParamName"] = "参数名称",
            ["Navigation_Hint_LowerLimit"] = "下限",
            ["Navigation_Hint_UpperLimit"] = "上限",
            ["Navigation_Hint_Unit"] = "单位",
            ["Navigation_Tooltip_DeleteParam"] = "删除参数",
            ["Navigation_Recipe_CloudSource"] = "云端配方",
            ["Navigation_Recipe_LocalSource"] = "本地配方",
            ["Navigation_Recipe_NotLoaded"] = "未加载",
            ["Navigation_Recipe_SyncFailed"] = "配方同步失败，请检查网络连接。",
            ["Navigation_Recipe_SyncSuccess"] = "云端配方已同步。",
            ["Navigation_Recipe_LocalSaveSuccess"] = "本地配方参数已保存。",
            ["Navigation_Recipe_SelectLocalParamToDelete"] = "请选择要删除的本地配方参数。",
            ["Navigation_Recipe_LocalDeleteSuccess"] = "本地配方参数已删除。",
            ["Navigation_Recipe_Validation_ParamNameRequired"] = "本地配方参数名称不能为空。",
            ["Navigation_Recipe_Validation_MinNumber"] = "最小值必须是有效数字。",
            ["Navigation_Recipe_Validation_MaxNumber"] = "最大值必须是有效数字。",
            ["Navigation_Recipe_Validation_MinLessEqualMax"] = "最小值不能大于最大值。",
            ["Navigation_Param_SaveSuccess"] = "参数配置已保存。",
            ["Navigation_Param_SaveFailed"] = "参数配置保存失败。",
            ["Navigation_Param_NoPermission"] = "当前用户没有参数配置权限。",

            ["Navigation_Diagnostics_RuntimeNotStarted"] = "本批只验证 UI 注册和页面加载，后台运行链路未启动。"
        };
}

public sealed class NavigationAvaloniaEnUsResources : IAvaloniaResourceContributor
{
    public string CultureName => "en-US";

    public IReadOnlyDictionary<string, string> GetResources()
        => new Dictionary<string, string>
        {
            ["Navigation_Menu_Data"] = "Data",
            ["Navigation_Menu_Capacity"] = "Capacity",
            ["Navigation_Menu_HardwareConfig"] = "Hardware Config",
            ["Navigation_Menu_Monitor"] = "Monitor",
            ["Navigation_Menu_Io"] = "I/O",
            ["Navigation_Menu_Recipe"] = "Recipe",
            ["Navigation_Menu_ParamConfig"] = "Parameters",
            ["Navigation_Menu_PlcTaskBinding"] = "PLC Tasks",
            ["Navigation_Menu_CoreDiagnostics"] = "Diagnostics",
            ["Navigation_Title_IoInteract"] = "I/O Interaction",
            ["Navigation_Title_HardwareConfig"] = "Hardware Config",
            ["Navigation_Title_ProductRecipe"] = "Product Recipe",
            ["Navigation_Title_ParamConfig"] = "Parameter Configuration",
            ["Navigation_Title_IoInteractionGroup"] = "Interaction Points",

            ["Navigation_Tab_NetworkDevice"] = "Network Devices",
            ["Navigation_Tab_SerialDevice"] = "Serial Devices",
            ["Navigation_Tab_IoMapping"] = "I/O Mapping",
            ["Navigation_Tab_MesParams"] = "MES Parameters",
            ["Navigation_Tab_CloudParams"] = "Cloud Parameters",
            ["Navigation_Tab_PluginBusinessParams"] = "Plugin Business Parameters",

            ["Navigation_Button_Query"] = "Query",
            ["Navigation_Button_Export"] = "Export",
            ["Navigation_Button_Save"] = "Save",
            ["Navigation_Button_SyncCloud"] = "Sync Cloud",
            ["Navigation_Button_SwitchSource"] = "Switch Source",
            ["Navigation_Button_Add"] = "Add",
            ["Navigation_Button_Delete"] = "Delete",
            ["Navigation_Button_Cancel"] = "Cancel",
            ["Navigation_Button_Confirm"] = "Confirm",
            ["Navigation_Button_Write"] = "Write",
            ["Navigation_Button_AddInteraction"] = "Add Interaction",
            ["Navigation_Button_AddDataPoint"] = "Add Data Point",

            ["Navigation_Column_Time"] = "Time",
            ["Navigation_Column_BatchNo"] = "Batch",
            ["Navigation_Column_Total"] = "Total",
            ["Navigation_Column_Ok"] = "OK",
            ["Navigation_Column_Ng"] = "NG",
            ["Navigation_Column_Yield"] = "Yield",
            ["Navigation_Column_DeviceName"] = "Device",
            ["Navigation_Column_DeviceType"] = "Type",
            ["Navigation_Column_DeviceModel"] = "Model",
            ["Navigation_Column_ModuleId"] = "Module",
            ["Navigation_Column_IpAddress"] = "IP Address",
            ["Navigation_Column_Port1"] = "Port 1",
            ["Navigation_Column_Port2"] = "Port 2",
            ["Navigation_Column_Command1"] = "Command 1",
            ["Navigation_Column_Command2"] = "Command 2",
            ["Navigation_Column_TimeoutMs"] = "Timeout(ms)",
            ["Navigation_Column_Enable"] = "Enabled",
            ["Navigation_Column_Remark"] = "Remark",
            ["Navigation_Column_PortName"] = "Port",
            ["Navigation_Column_BaudRate"] = "Baud Rate",
            ["Navigation_Column_DataBits"] = "Data Bits",
            ["Navigation_Column_StopBits"] = "Stop Bits",
            ["Navigation_Column_Parity"] = "Parity",
            ["Navigation_Column_PlcAddress"] = "PLC Address",
            ["Navigation_Column_Count"] = "Count",
            ["Navigation_Column_BusinessGroup"] = "Business Group",
            ["Navigation_Column_SignalName"] = "Signal Name",
            ["Navigation_Column_DataType"] = "Data Type",
            ["Navigation_Column_Direction"] = "Direction",
            ["Navigation_Column_Editable"] = "Editable",
            ["Navigation_Column_Status"] = "Status",
            ["Navigation_Column_Message"] = "Message",
            ["Navigation_Column_TaskKey"] = "Task Key",
            ["Navigation_Column_Signal"] = "Signal",
            ["Navigation_Column_Binding"] = "Binding",
            ["Navigation_Column_Address"] = "Address",
            ["Navigation_Column_CurrentValue"] = "Current Value",
            ["Navigation_Column_InteractionItem"] = "Interaction",
            ["Navigation_Column_PlcSignal"] = "PLC Signal",
            ["Navigation_Column_PlcValue"] = "PLC Value",
            ["Navigation_Column_CurrentReply"] = "Current Reply",
            ["Navigation_Column_ReplyValue"] = "Reply Value",
            ["Navigation_Column_WriteValue"] = "Write Value",
            ["Navigation_Column_Action"] = "Action",
            ["Navigation_Column_Index"] = "Index",
            ["Navigation_Column_MatrixValues"] = "Matrix Values",
            ["Navigation_Column_ParamName"] = "Parameter Name",
            ["Navigation_Column_ParamValue"] = "Parameter Value",
            ["Navigation_Column_ParamType"] = "Parameter Type",
            ["Navigation_Column_DefaultValue"] = "Default Value",
            ["Navigation_Column_LowerLimit"] = "Lower Limit",
            ["Navigation_Column_UpperLimit"] = "Upper Limit",
            ["Navigation_Column_Unit"] = "Unit",

            ["Navigation_Dialog_Title_Pending"] = "Pending",
            ["Navigation_Dialog_Message_Pending"] = "Please confirm this operation.",
            ["Navigation_Dialog_AddIoPoint"] = "Add I/O Point",
            ["Navigation_Dialog_AddInteraction"] = "A new interaction point will be added to the selected network device.",
            ["Navigation_Dialog_AddDataPoint"] = "A new data point will be added to the selected network device.",
            ["Navigation_Dialog_Title_SaveHardwareConfig"] = "Save Hardware Config",
            ["Navigation_Dialog_Message_SaveHardwareConfigReadonly"] = "This is an Avalonia migration validation and will not write real hardware configuration.",
            ["Navigation_Status_ReadOnlyValidation"] = "Read-only validation mode",
            ["Navigation_Status_AddInteractionPending"] = "Add interaction point pending",
            ["Navigation_Status_AddDataPointPending"] = "Add data point pending",
            ["Navigation_Status_SavePending"] = "Save confirmation pending",

            ["Navigation_Io_ManualRead"] = "Manual Read",
            ["Navigation_Io_NoSignals"] = "No I/O points are available for this device.",
            ["Navigation_Io_DemoDeviceA"] = "PLC Interaction Station A",
            ["Navigation_Io_DemoDeviceB"] = "PLC Data Station B",
            ["Navigation_Io_SafeSkeletonMessage"] = "This Avalonia I/O shell does not connect manual reads or writes to a real PLC.",
            ["Navigation_Io_ManualReadPreviewUpdated"] = "Preview values were refreshed without connecting to a real PLC.",
            ["Navigation_Io_WriteRejected"] = "The write request was rejected by the safe port.",
            ["Navigation_Io_WritePreviewUpdated"] = "Write preview values were updated without connecting to a real PLC.",
            ["Navigation_Io_Direction_PlcToHost"] = "PLC to host",
            ["Navigation_Io_Direction_HostToPlc"] = "Host to PLC",
            ["Navigation_Io_CollapseDetails"] = "Collapse",
            ["Navigation_Io_ViewDetails"] = "View Details",
            ["Navigation_Io_NoContinuousValues"] = "No continuous values",
            ["Navigation_Io_ArraySummaryFormat"] = "{0} rows x {1} items",
            ["Navigation_ListSeparator"] = ", ",

            ["Navigation_Label_Version"] = "Version",
            ["Navigation_Label_Process"] = "Process",
            ["Navigation_Label_Update"] = "Updated",
            ["Navigation_Label_Source"] = "Source",
            ["Navigation_Label_EmergencyEdit"] = "Local Emergency Edit",
            ["Navigation_Hint_ParamName"] = "Parameter Name",
            ["Navigation_Hint_LowerLimit"] = "Lower Limit",
            ["Navigation_Hint_UpperLimit"] = "Upper Limit",
            ["Navigation_Hint_Unit"] = "Unit",
            ["Navigation_Tooltip_DeleteParam"] = "Delete parameter",
            ["Navigation_Recipe_CloudSource"] = "Cloud Recipe",
            ["Navigation_Recipe_LocalSource"] = "Local Recipe",
            ["Navigation_Recipe_NotLoaded"] = "Not Loaded",
            ["Navigation_Recipe_SyncFailed"] = "Recipe sync failed. Check the network connection.",
            ["Navigation_Recipe_SyncSuccess"] = "Cloud recipe synchronized.",
            ["Navigation_Recipe_LocalSaveSuccess"] = "Local recipe parameter saved.",
            ["Navigation_Recipe_SelectLocalParamToDelete"] = "Select a local recipe parameter to delete.",
            ["Navigation_Recipe_LocalDeleteSuccess"] = "Local recipe parameter deleted.",
            ["Navigation_Recipe_Validation_ParamNameRequired"] = "Local recipe parameter name is required.",
            ["Navigation_Recipe_Validation_MinNumber"] = "Minimum must be a valid number.",
            ["Navigation_Recipe_Validation_MaxNumber"] = "Maximum must be a valid number.",
            ["Navigation_Recipe_Validation_MinLessEqualMax"] = "Minimum cannot be greater than maximum.",
            ["Navigation_Param_SaveSuccess"] = "Parameter configuration saved.",
            ["Navigation_Param_SaveFailed"] = "Parameter configuration save failed.",
            ["Navigation_Param_NoPermission"] = "Current user does not have parameter configuration permission.",

            ["Navigation_Diagnostics_RuntimeNotStarted"] = "This batch validates UI registration and page loading only; backend runtime is not started."
        };
}
